# Расчет признаков. 
## Взяты первые матрицы из таблицы 
1. P полож(резк)
2. P(1-10)

In [99]:
import quantecon as qe
import numpy as np
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
%matplotlib inline

In [100]:
P1=[[0.0232460593460577, 0.00560174845597652, 0.0467179883425076, 0.0665592773073191, 0.857874926548139],
     [0.0136463870422535, 0.0490583821470984, 0.0166987360598636, 0.1296937249811, 0.790902769769684],
      [0.0462073802724979, 0.00163516165267978, 0.0122184468821205, 0.00806716298524617, 0.931871848207456],
      [0.0674564304316847, 0.118393449396849, 0.0945556903438833, 0.0289925763492009, 0.690601853478382],
     [0.0719504828182986, 0.237872699666635, 0.137118006112976, 0.0391436205590491, 0.513915190843042]]

In [101]:
#создаем экземпляр цепи маркова
mc=qe.MarkovChain(P1)
print(mc)

<bound method MarkovChain.__repr__ of Markov chain with transition matrix 
P = 
[[0.02324606 0.00560175 0.04671799 0.06655928 0.85787493]
 [0.01364639 0.04905838 0.01669874 0.12969372 0.79090277]
 [0.04620738 0.00163516 0.01221845 0.00806716 0.93187185]
 [0.06745643 0.11839345 0.09455569 0.02899258 0.69060185]
 [0.07195048 0.2378727  0.13711801 0.03914362 0.51391519]]>


In [102]:
#Проверим на разложимость (данная матрица неразложима)
mc.is_irreducible

True

In [103]:
#Данная цепь образует 1 неразложимый класс
mc.num_communication_classes

1

In [104]:
mc.communication_classes

[array([0, 1, 2, 3, 4])]

In [105]:
mc.recurrent_classes

[array([0, 1, 2, 3, 4])]

In [106]:
#Проверим на апериодичность (данная матрица переодична)
mc.is_aperiodic

True

In [107]:
#Период
mc.period

1

In [108]:
mc.simulate(12,init=0)

array([0, 4, 1, 4, 2, 4, 2, 4, 2, 4, 2, 4])

In [109]:
P2=[[0.003407870408, 0.01806985987, 0.01954364792, 0.01666851099, 0.9423101108],
    [0.04513286019, 0.03464884503, 0.004095797233, 0.002455417135, 0.9136670804],
    [0.04253086727, 0.003216659271, 0.1020704951, 0.005207838836, 0.8469741396],
    [0.05805748631, 0.01464032011, 0.004289838442, 0.02608821783, 0.8969241373],
    [0.04400335537, 0.05817956438, 0.004399909611, 0.01972704556, 0.8736901251]]

In [110]:
mc2=qe.MarkovChain(P2)
print(mc2)

<bound method MarkovChain.__repr__ of Markov chain with transition matrix 
P = 
[[0.00340787 0.01806986 0.01954365 0.01666851 0.94231011]
 [0.04513286 0.03464885 0.0040958  0.00245542 0.91366708]
 [0.04253087 0.00321666 0.1020705  0.00520784 0.84697414]
 [0.05805749 0.01464032 0.00428984 0.02608822 0.89692414]
 [0.04400336 0.05817956 0.00439991 0.01972705 0.87369013]]>


In [111]:
#Проверим на разложимость (данная матрица неразложима)
mc2.is_irreducible

True

In [112]:
mc2.num_communication_classes

1

In [113]:
mc2.communication_classes

[array([0, 1, 2, 3, 4])]

In [114]:
mc2.recurrent_classes

[array([0, 1, 2, 3, 4])]

In [115]:
#Проверим на апериодичность
mc2.is_aperiodic

True

In [116]:
#Период
mc2.period

1

In [117]:
mc2.simulate(12,init=0)

array([0, 4, 4, 4, 0, 4, 3, 0, 4, 1, 0, 4])

In [118]:
P3=[[0.03981050242,0.06495668917,0.03857361881,0.03042645428,0.8262327353],
[0.02784335616,0.007737903625,0.005239314131,0.01637654126,0.9428028848],
[0.09831946025,0.05926588909,0.05143485484,0.1005747777,0.6904050181],
[0.03524268554,0.04474536887,0.06311672581,0.05203553997,0.8048596798],
[0.04109990146,0.02135395227,0.04146709912,0.03515125786,0.8609277893]]

In [119]:
mc3=qe.MarkovChain(P3)
print(mc3)

<bound method MarkovChain.__repr__ of Markov chain with transition matrix 
P = 
[[0.0398105  0.06495669 0.03857362 0.03042645 0.82623274]
 [0.02784336 0.0077379  0.00523931 0.01637654 0.94280288]
 [0.09831946 0.05926589 0.05143485 0.10057478 0.69040502]
 [0.03524269 0.04474537 0.06311673 0.05203554 0.80485968]
 [0.0410999  0.02135395 0.0414671  0.03515126 0.86092779]]>


In [120]:
mc3.is_irreducible

True

In [121]:
mc3.num_communication_classes

1

In [122]:
mc3.communication_classes

[array([0, 1, 2, 3, 4])]

In [123]:
mc3.recurrent_classes

[array([0, 1, 2, 3, 4])]

In [124]:
#Проверим на апериодичность
mc3.is_aperiodic

True

In [125]:
#Период
mc3.period

1

In [126]:
mc3.simulate(12,init=0)

array([0, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 4])

In [127]:
P4=[[0.0355290328,0.04511749448,0.02287085724,0.01315736716,0.8833252483],
[0.01868372706,0.1299598041,0.1203421242,0.0682766782,0.6627376665],
[0.005528940424,0.0389864698,0.03167713187,0.02736129022,0.8964461677],
[0.1451803416,0.03038348942,0.0268245473,0.06509280771,0.7325188139],
[0.07278494759,0.07677333778,0.008415631524,0.03454222864,0.8074838545]]

In [128]:
mc4=qe.MarkovChain(P4)
print(mc4)

<bound method MarkovChain.__repr__ of Markov chain with transition matrix 
P = 
[[0.03552903 0.04511749 0.02287086 0.01315737 0.88332525]
 [0.01868373 0.1299598  0.12034212 0.06827668 0.66273767]
 [0.00552894 0.03898647 0.03167713 0.02736129 0.89644617]
 [0.14518034 0.03038349 0.02682455 0.06509281 0.73251881]
 [0.07278495 0.07677334 0.00841563 0.03454223 0.80748385]]>


In [129]:
mc4.is_irreducible

True

In [130]:
mc4.num_communication_classes

1

In [131]:
mc4.communication_classes

[array([0, 1, 2, 3, 4])]

In [132]:
mc4.recurrent_classes

[array([0, 1, 2, 3, 4])]

In [133]:
#Проверим на апериодичность
mc4.is_aperiodic

True

In [134]:
#Период
mc4.period

1

In [135]:
mc4.simulate(12,init=0)

array([0, 4, 4, 4, 4, 4, 4, 4, 0, 4, 4, 4])

In [136]:
P5=[[0,0.2197192828,0.196783264,0.2492150375,0.3342824158],
[0.2774944612,0,0.2612031801,0.2218092767,0.2394930821],
[0.08406331128,0.171050228,0.5547862007,0,0.19010026],
[0,0.08507360996,0.2230691724,0.332791398,0.3590658196],
[0,0.2576231624,0.1501625937,0.4686043822,0.1236098617]]

In [137]:
mc5=qe.MarkovChain(P5)
print(mc5)

<bound method MarkovChain.__repr__ of Markov chain with transition matrix 
P = 
[[0.         0.21971928 0.19678326 0.24921504 0.33428242]
 [0.27749446 0.         0.26120318 0.22180928 0.23949308]
 [0.08406331 0.17105023 0.5547862  0.         0.19010026]
 [0.         0.08507361 0.22306917 0.3327914  0.35906582]
 [0.         0.25762316 0.15016259 0.46860438 0.12360986]]>


In [138]:
mc5.is_irreducible

True

In [139]:
mc5.num_communication_classes

1

In [140]:
mc5.communication_classes

[array([0, 1, 2, 3, 4])]

In [141]:
mc5.recurrent_classes

[array([0, 1, 2, 3, 4])]

In [142]:
#Проверим на апериодичность
mc5.is_aperiodic

True

In [143]:
#Период
mc5.period

1

In [144]:
mc5.simulate(12,init=0)

array([0, 4, 3, 4, 2, 1, 0, 3, 3, 4, 1, 0])

In [145]:
P6=[[0.04093156809,0.04848782226,0.01811129584,0.04667921601,0.8457900978],
[0.01979243132,0.08594862759,0.04605026383,0.0391250939,0.8090835834],
[0.05491338482,0.04519347815,0.005125657309,0.04394498524,0.8508224945],
[0.03964469824,0.0517019057,0.004791790746,0.01350249567,0.8903591096],
[0.1155835332,0.1117185882,0.07976275684,0.04276391592,0.6501712059]]

In [146]:
mc6=qe.MarkovChain(P6)
print(mc6)

<bound method MarkovChain.__repr__ of Markov chain with transition matrix 
P = 
[[0.04093157 0.04848782 0.0181113  0.04667922 0.8457901 ]
 [0.01979243 0.08594863 0.04605026 0.03912509 0.80908358]
 [0.05491338 0.04519348 0.00512566 0.04394499 0.85082249]
 [0.0396447  0.05170191 0.00479179 0.0135025  0.89035911]
 [0.11558353 0.11171859 0.07976276 0.04276392 0.65017121]]>


In [147]:
#Проверим на разложимость (данная матрица неразложима)
mc6.is_irreducible

True

In [148]:
#Данная цепь образует 1 неразложимый класс
mc6.num_communication_classes

1

In [149]:
mc6.communication_classes

[array([0, 1, 2, 3, 4])]

In [150]:
mc6.recurrent_classes

[array([0, 1, 2, 3, 4])]

In [151]:
#Проверим на апериодичность
mc6.is_aperiodic

True

In [152]:
#Период
mc6.period

1

In [153]:
P7=[[0.00685563054,0.01640025695,0.05036619569,0.01733671135,0.9090412055],
[0.04307637385,0.04898340216,0.01226181288,0.02336216372,0.8723162474],
[0.04578771588,0.02969407768,0.01169955505,0.01928774273,0.8935309087],
[0.006429347006,0.162530292,0.02697881973,0.08820610567,0.7158554356],
[0.004705016515,0.006198664368,0.04393713989,0.01195245438,0.9332067248]]

In [154]:
mc7=qe.MarkovChain(P7)
print(mc7)

<bound method MarkovChain.__repr__ of Markov chain with transition matrix 
P = 
[[0.00685563 0.01640026 0.0503662  0.01733671 0.90904121]
 [0.04307637 0.0489834  0.01226181 0.02336216 0.87231625]
 [0.04578772 0.02969408 0.01169956 0.01928774 0.89353091]
 [0.00642935 0.16253029 0.02697882 0.08820611 0.71585544]
 [0.00470502 0.00619866 0.04393714 0.01195245 0.93320672]]>


In [155]:
#Проверим на разложимость (данная матрица неразложима)
mc7.is_irreducible

True

In [156]:
#Данная цепь образует 1 неразложимый класс
mc7.num_communication_classes

1

In [157]:
mc7.communication_classes

[array([0, 1, 2, 3, 4])]

In [158]:
mc7.recurrent_classes

[array([0, 1, 2, 3, 4])]

In [159]:
#Проверим на апериодичность
mc7.is_aperiodic

True

In [160]:
#Период
mc7.period

1

In [179]:
P8=[[0.034966972, 0.019001252, 0.007437212, 0.021869966, 0.916724599],
[0.067111946, 0.038841389, 0.03761967, 0.004851325, 0.85157567],
[0.178412305, 0.056370555, 0.053259225, 0.013091102, 0.698866812],
[0.033934975, 0.041621044, 0.044161263, 0.023206893, 0.857075826],
[0.006062262, 0.01045856, 0.011370976, 0.036688231, 0.935419971]]

In [180]:
mc8=qe.MarkovChain(P8)
print(mc8)

<bound method MarkovChain.__repr__ of Markov chain with transition matrix 
P = 
[[0.03496697 0.01900125 0.00743721 0.02186997 0.9167246 ]
 [0.06711195 0.03884139 0.03761967 0.00485133 0.85157567]
 [0.1784123  0.05637056 0.05325923 0.0130911  0.69886681]
 [0.03393497 0.04162104 0.04416126 0.02320689 0.85707583]
 [0.00606226 0.01045856 0.01137098 0.03668823 0.93541997]]>


In [163]:
#Проверим на разложимость (данная матрица неразложима)
mc8.is_irreducible

True

In [164]:
#Данная цепь образует 1 неразложимый класс
mc8.num_communication_classes

1

In [165]:
mc8.communication_classes

[array([0, 1, 2, 3, 4])]

In [166]:
mc8.recurrent_classes

[array([0, 1, 2, 3, 4])]

In [167]:
#Проверим на апериодичность
mc8.is_aperiodic

True

In [168]:
#Период
mc8.period

1

In [181]:
P9=[[0.2742977627,0.2394912027,0.276237029,0.1056719555,0.1043020501],
[0.1398976015,0.1623782033,0.3020108674,0.1596085543,0.2361047735],
[0.2414420747,0.3230767145,0.06819123067,0.2063146567,0.1609753234],
[0.01602688416,0.06732822475,0.4000845743,0.2186780297,0.2978822871],
[0.4694208784,0.04464894679,0.09831647976,0.3673226193,0.02029107578]]

In [182]:
mc9=qe.MarkovChain(P9)
print(mc9)

<bound method MarkovChain.__repr__ of Markov chain with transition matrix 
P = 
[[0.27429776 0.2394912  0.27623703 0.10567196 0.10430205]
 [0.1398976  0.1623782  0.30201087 0.15960855 0.23610477]
 [0.24144207 0.32307671 0.06819123 0.20631466 0.16097532]
 [0.01602688 0.06732822 0.40008457 0.21867803 0.29788229]
 [0.46942088 0.04464895 0.09831648 0.36732262 0.02029108]]>


In [183]:
#Проверим на разложимость (данная матрица неразложима)
mc9.is_irreducible

True

In [184]:
#Данная цепь образует 1 неразложимый класс
mc9.num_communication_classes

1

In [185]:
mc9.communication_classes

[array([0, 1, 2, 3, 4])]

In [186]:
mc9.recurrent_classes

[array([0, 1, 2, 3, 4])]

In [187]:
#Проверим на апериодичность
mc9.is_aperiodic

True

In [188]:
#Период
mc9.period

1

In [195]:
P10=[[0.556054913,0.443945087,0,0,0],
[0,0,0.6155749056,0.3844250944,0],
[0.4700347821,0,0,0,0.5299652179],
[0,0.2140780838,0.7859219162,0,0],
[0,0,0.633299081,0.366700919,0]]

In [196]:
mc10=qe.MarkovChain(P10)
print(mc10)

<bound method MarkovChain.__repr__ of Markov chain with transition matrix 
P = 
[[0.55605491 0.44394509 0.         0.         0.        ]
 [0.         0.         0.61557491 0.38442509 0.        ]
 [0.47003478 0.         0.         0.         0.52996522]
 [0.         0.21407808 0.78592192 0.         0.        ]
 [0.         0.         0.63329908 0.36670092 0.        ]]>


In [197]:
#Проверим на разложимость (данная матрица неразложима)
mc10.is_irreducible

True

In [198]:
#Данная цепь образует 1 неразложимый класс
mc10.num_communication_classes

1

In [199]:
mc10.communication_classes

[array([0, 1, 2, 3, 4])]

In [200]:
mc10.recurrent_classes

[array([0, 1, 2, 3, 4])]

In [201]:
#Проверим на апериодичность
mc10.is_aperiodic

True

In [202]:
#Период
mc10.period

1

**Заключение:** Данные матрицы были рассмотрены на свойства (разложимость, переодичность, количество периодов и количество неразложимых классов).

Марковские свойства оказались у всех матриц похожими, т.к. присутствует очень большая точность в данных.